install.packages("caret", repos="http://cran.us.r-project.org")
install.packages("devtools", repos="http://cran.us.r-project.org")
install.packages("lexicon", repos="http://cran.us.r-project.org")
install.packages("plumber", repos="http://cran.us.r-project.org")
install.packages("stm", repos="http://cran.us.r-project.org")
install.packages("stringi", repos="http://cran.us.r-project.org")
install.packages("stringr", repos="http://cran.us.r-project.org")
install.packages("tm", repos="http://cran.us.r-project.org")
install.packages("tau", repos="http://cran.us.r-project.org")
install.packages("stopwords", repos="http://cran.us.r-project.org")
install.packages("textclean", repos="http://cran.us.r-project.org")
devtools::install_version("quanteda", version="1.2.0", repos="http://cran.us.r-project.org")
install.packages("testthat", repos="http://cran.us.r-project.org")
install.packages("here", repos="http://cran.us.r-project.org")
install.packages("futile.logger", repos="http://cran.us.r-project.org")
install.packages("ngram", repos="http://cran.us.r-project.org")
install.packages("R.utils", repos="http://cran.us.r-project.org")
install.packages("rlist", repos="http://cran.us.r-project.org")